== Summary
The Geospatial to the Edge Interoperability Plugfest, co-sponsored by the Army Geospatial Center and the National Geospatial-Intelligence Agency (NGA/CIO&T), brought together technology implementers and data providers to advance the interoperability of geospatial products and services based on profiles of OGC standards. Specifically, servers and data available via GeoPackage, Web Feature Service (WFS), Web Map Service (WMS), and Web Map Tile Service (WMTS), all following National System for Geospatial Intelligence (NSG) profiles, were exercised and improved in various clients. Compliance Tests were executed and advanced based on feedback from the participants.


=== Motivation
The geospatial communities supporting defense, emergency response, and intelligence rely on geospatial data and open standards to accomplish their missions. Profiles of standards and data models were used to ensure sharing of data meet their specific needs. Profiles provide strict implementation guidance to ensure interoperability of geospatial systems and data in these highly specialized and demanding environments. Implementations following profiles compliant with open standards support mission critical operations for enhancing effective and efficient execution.

A Plugfest is an initiative of the OGC Innovation Program. Plugfests provides the right venue for sponsors and technology implementers to come together in a collaborative agile process to solve geospatial challenges. The Plugfest assisted tool enhancement and provided guidance to improve the delivery of enterprise geospatial data to end users. In this initiative, a Plugfest was used to bring more than thirteen data/service producers and clients of data following NSG profiles. The plugfest help discover implementation issues and advance executable test suites.


=== Prior-after comparison

Before the Plugfest, very few implementations were able to interact with NSG profiles of OGC standards. This is commonly the case when communities want to restrict a rule from the base standard or want to extend what the base standard offers. Support for NSG profiles is not commonly a feature that comes packaged in software products. After the Plugfest more implementations became available that implement the NSG profiles for GeoPackage, WMS, WFS, and WMTS.

The profiles implemented in the Plugfest had corresponding executable test suites. These profiles test suites were in beta by the end of the initiative, ready to be move forward for public release by the OGC Technical Committee. Feedback related to the executable test suites was provided by the participants. In particular, the GeoPackage test was improved during the Plugfest.


=== Recommendations for future work

Plugfests should be performed for any new profile of an existing OGC standard or any new candidate OGC standard including revisions. Allowing participants to come together to solve interoperability issues has high value in maturing and stress testing implementations of profiles or candidate standards. The result, of high value to the geospatial community, is improvement of the standards and advancement of test suites.

Recommendations for implementing the profiles in regards to the specific profiles are detailed in the <<Results,Results and Recommendations>> Section.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Luis Bermudez | OGC
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
