== Summary
The Geospatial to the Edge Interoperability Plugfest, co-sponsored by Army Geospatial Center and the National Geospatial-Intelligence Agency (NGA/CIO&T) brought together technology implementers and data providers to advance the interoperability of geospatial products and services based on OGC profiles. Servers and data available via GeoPackage, WFS, WMS and WMTS, all following National System for Geospatial Intelligence (NSG) profiles were exercised and improved in various clients. Compliance Tests were executed and advanced based on feedback from the participants.


=== Motivation
The geospatial communities supporting defense, emergency response, and intelligence rely on geospatial data and open standards to accomplish their mission. To make sharing of data meet their specific needs, they used profiles. Profiles provide strict implementation guidance to ensure interoperability of geospatial systems in these highly specialized and demanding environments. Implementations following profiles compliant to open standards support mission critical operations for executing effectively and efficiently.

A Plugfest, an initiative of the OGC Innovation Program [http://www.opengeospatial.org/ogc/programs/ip], provides the right venue for sponsors and technology implementers to come together in a collaborative agile process to solve geospatial challenges. The Plugfest assisted tool enhancement and provided guidance to improve the delivery of enterprise geospatial data to end users. In this initiative, a Plugfest was used to bring more than thirteen data/service producers and clients of data following NSG profiles. It help discovered implementation issues and advance executable test suites.



=== Prior-after comparison

Before the Plugfest very few implementations were able to interact with NSG profiles. This is commonly the case when communities want to restrict a rule from the base standard or want to extend what the base standard offers. The support for these profiles is not commonly a feature that comes packaged in software products. After the Plugfest more implementations were available implementing the NSG profiles.

The profiles implemented in the Plugfest had corresponding executable test suites. These profiles test suites were in beta by the end of the initiative, ready to be move forward for public release by the OGC Technical Committee.  Feedback related to the executable test suites was provided by the participants. In particular, the GeoPackage test was improved during the Plugfest.


=== Recommendations for future work

Activities like this Plugfest should be performed for new profiles or new standards allowing participants to come together to solve interoperability issues. The result, of high value to the geospatial community, is improvement of the standards and advancement of test suites.

Recommendations about implementing the profiles in regards to the specific profiles are detailed in the <<Results,Results and Recommendations>> Section.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Luis Bermudez | OGC
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
