== Summary
The Geospatial to the Edge Interoperability Plugfest, co-sponsored by Army Geospatial Center and the National Geospatial-Intelligence Agency (NGA/CIO&T) brought together technology implementers and data providers to advance the interoperability of geospatial products and services based on OGC profiles.


=== Motivation
The geospatial communities supporting defense, emergency response, and intelligence rely on geospatial data and open standards to accomplish their mission. To make sharing of data meet their specific needs, they used profiles. Profiles provide strict implementation guidance to ensure interoperability of geospatial systems in these highly specialized and demanding environments. Non-compliance to open standards profiles prohibits mission critical operations from executing effectively and efficiently.

A plugfest, an initiative of the OGC Innovation Program [http://www.opengeospatial.org/ogc/programs/ip], provides the right venue for sponsors and technology implementers to come together in a collaborative agile process to solve geospatial challenges. The Plugfest assisted tool enhancement and provided guidance to improve the delivery of enterprise geospatial data to end users. In this initiative, the plugfest was used to bring more than ten data/service producers and clients of data following NSG profiles. It help discovered implementation issues and advance executable test suites.



=== Prior-After Comparison

Before the Plugfest very few implementations were able to interact with NGS profiles. After the plugfest more implementations were available.

The executable test suites were also improved as a results of feedback form the participants.


=== Recommendations for Future Work

Activities like this plugest should be performed for new profiles allowing participating to come together and tests to be advanced.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Luis Bermudez | OGC
|((contributor)) | ((from org))
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
