[[Overview]]
== Overview

This OGC Plugfest, co-sponsored by Army Geospatial Center and the National Geospatial-Intelligence Agency (NGA/CIO&T), brought together technology implementers and data providers to advance the interoperability of geospatial products and services based on community profiles of existing OGC standards . The Plugfest assisted in tool enhancement and provided guidance to improve the delivery of enterprise geospatial data to end users.

Examples of how end user communities will benefit from this work are:

- First responders, relief workers and fire fighters preparing for and operating in austere network environments;
- Emergency planners and managers supporting hurricane, wildfire, and earthquake preparedness,  relief/response activities and damage assessment; and
- Soldiers/warfighters during planning and executing operations specifically in disconnected, intermittent, and limited network environments.

The geospatial communities supporting defense, emergency response, and intelligence rely on geospatial data and open standards to accomplish their mission. To make sharing of data meet their specific needs, they require the definition, testing, and community approval of profiles of existing OGC standards. Profiles provide strict implementation guidance to ensure interoperability of geospatial systems in these highly specialized and demanding environments. Non-compliance to open standards profiles prohibits mission critical operations from executing effectively and efficiently.

NOTE: The OGC membership recently approved an official definition of the concept ”profile” that includes the case in which a profile extends the base standard. NSG Profiles are of the latter type of profile and in the future these types of profiles should be referred as Profiles with Extension. Profiles restrict (remove) options (e.g., file formats or coordinate reference systems) that may be specified in the base standard. GML Simple Features is an example of a profile that restricts the number of requirements to be implemented. Extensions add options and/or capabilities that are not included in the base standard.

Additionally, members of the Intelligence Community (IC), United States Department of Defense (DoD), non-DoD/IC Federal agency members of the NSG, international partners, state/local municipalities, and Native American tribal organizations that are responsible for the operation, acquisition and/or development of systems and applications which collect, procure, produce, serve, exchange, or use Geospatial Intelligence (GEOINT) data are mandated to comply with NSG implementation standards (NSGM 3202). Support of these standards, which may be profiles of OGC standards, affect government acquisition decisions to ensure that all systems within the government can communicate appropriately. [From GEOINT Functional Manager Standards Assessment (GFMSA) Program Manual, NSGM 3202, June 2016]

A Plugfest, an initiative of the OGC Innovation Program, provides a collaborative venue for sponsors and technology implementers to come together in a agile process to solve geospatial challenges. A plugfest provides the scenario and testing environment to advance implementation of profiles in commercial and open source software products. A Plugfest allows organizations to test and validate that their software products can interoperate with other products implementing the same standard or profiles of a standard.
